// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwphkicjrPMUSYXBdW-wBGoqderFJpH0A',
    appId: '1:269831612373:web:97b7242ab21a8d8589ff5c',
    messagingSenderId: '269831612373',
    projectId: 'spotify0101-9dde3',
    authDomain: 'spotify0101-9dde3.firebaseapp.com',
    storageBucket: 'spotify0101-9dde3.firebasestorage.app',
    measurementId: 'G-CF9DNBVKRS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQelcHSZPzQv9N1iOuPhDCdsgM4O49tV0',
    appId: '1:269831612373:android:c649001634db48dd89ff5c',
    messagingSenderId: '269831612373',
    projectId: 'spotify0101-9dde3',
    storageBucket: 'spotify0101-9dde3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGY36_JpaLWEdJpCjBMmJ2uaNM2zdoM1o',
    appId: '1:269831612373:ios:ef5c7819ec1b446c89ff5c',
    messagingSenderId: '269831612373',
    projectId: 'spotify0101-9dde3',
    storageBucket: 'spotify0101-9dde3.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwphkicjrPMUSYXBdW-wBGoqderFJpH0A',
    appId: '1:269831612373:web:658fd38e4745015d89ff5c',
    messagingSenderId: '269831612373',
    projectId: 'spotify0101-9dde3',
    authDomain: 'spotify0101-9dde3.firebaseapp.com',
    storageBucket: 'spotify0101-9dde3.firebasestorage.app',
    measurementId: 'G-Q88LVJQZ62',
  );
}
