// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU9Q_DeMKJKsKRKjBD5EehZZy222JFkXs',
    appId: '1:247765216945:web:e969751ceba172bc10bc90',
    messagingSenderId: '247765216945',
    projectId: 'flutterfirebase-7c449',
    authDomain: 'flutterfirebase-7c449.firebaseapp.com',
    databaseURL: 'https://flutterfirebase-7c449-default-rtdb.firebaseio.com',
    storageBucket: 'flutterfirebase-7c449.appspot.com',
    measurementId: 'G-BW342T6XRK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6MckJ62ApIDp8ttVcopgiGrhUYFWpI-Q',
    appId: '1:247765216945:android:543b450486bfa15b10bc90',
    messagingSenderId: '247765216945',
    projectId: 'flutterfirebase-7c449',
    databaseURL: 'https://flutterfirebase-7c449-default-rtdb.firebaseio.com',
    storageBucket: 'flutterfirebase-7c449.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ0JttgpRW90gbZTAaOb2w0MObaOzskf4',
    appId: '1:247765216945:ios:66ea34ae3d641c7510bc90',
    messagingSenderId: '247765216945',
    projectId: 'flutterfirebase-7c449',
    databaseURL: 'https://flutterfirebase-7c449-default-rtdb.firebaseio.com',
    storageBucket: 'flutterfirebase-7c449.appspot.com',
    androidClientId: '247765216945-6a3nk28c9emtrl33shj5jiu3unav53s4.apps.googleusercontent.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBU9Q_DeMKJKsKRKjBD5EehZZy222JFkXs',
    appId: '1:247765216945:web:a525564d97432f0b10bc90',
    messagingSenderId: '247765216945',
    projectId: 'flutterfirebase-7c449',
    authDomain: 'flutterfirebase-7c449.firebaseapp.com',
    databaseURL: 'https://flutterfirebase-7c449-default-rtdb.firebaseio.com',
    storageBucket: 'flutterfirebase-7c449.appspot.com',
    measurementId: 'G-YG2SCKS2B4',
  );

}